VALID_LOCATIONS = {
    "2004",
    "2005",
    "2007",
    "2013",
    "2015",
    "2017",
    "2019",
    "2110",
    "2115",
    "2117",
    "2119",
    "2125",
    "2130",
    "2135",
    "2145",
    "2150",
    "2155",
    "2165",
    "2175",
    "2204",
    "2205",
    "2206",
    "2210",
    "2215",
    "2220",
    "2221",
    "2225",
    "2227",
    "2231",
    "2235",
    "2240",
    "2250",
    "2255",
    "2260",
    "2300",
    "all gender restroom",
    "break room",
    "circulation room",
    "conference room",
    "devin scott office",
    "electrical",
    "event center kitchen",
    "guii lab",
    "instructors room",
    "mother’s room",
    "open computer lab",
    "student lounge",
    "university extension service center",
    "fire alarm",
    "men",
    "women",
    "janitor's closet",
    "event space",
    "restroom",
    "sip - speculating future mobility: exploring interaction in autonomous 'third spaces'",
    "sip project meetings",
    "summer academy on ai",
    "mobile interface design and gen ai",
    "devin sodt building operations supervisor",
    "pre-college lunch",
    "embedded firmware essentials",
    "human centered ai: how ai thinks",
    "sip - mentorship",
    "sip - cpm-05: speculative design of future ai-integrated healthy eating creator ecosystems on social media",
    "ece 2: introducción a la enseñanza de niños pequeños",
    "high school healthcare academy & human biology",
    "sip - compost facility level survey and policy efficacy evaluation",
    "it",
    "circulation"
}
