'''
This was generated by ChatGPT, I lwk don't know how it works
The main function here is call_llm, where you input a text and it calls llm with the text
Also there's a system_prompt you can edit here
'''



from __future__ import annotations

import os
from typing import Dict, List, Mapping, Optional, Sequence

from dotenv import load_dotenv
from openai import (
    APIConnectionError,
    APIStatusError,
    AuthenticationError,
    OpenAI,
    RateLimitError,
)


# ============================================================
# Configuration
# ============================================================

load_dotenv()

DEEPSEEK_BASE_URL = "https://api.deepseek.com"
MODEL_NAME = "deepseek-v4-flash"
MAX_CONVERSATION_USER_INPUTS = 10

ConversationMessage = Dict[str, str]


BELT_SYSTEM_PROMPT = """
You are BELT, a UCSC campus receptionist robot.

Your job is to communicate with visitors in a friendly, helpful,
and concise way.

Personality:
- Friendly
- Curious
- Helpful
- Slightly witty
- Patient with beginners

Rules:
- Keep responses short unless the user asks for more detail.
- Do not claim that you can see something unless computer vision
  information was explicitly provided.
- Do not claim that you moved or navigated somewhere unless the
  corresponding robot module confirmed that it happened.
- If you are uncertain, clearly say that you are not sure.
- Never invent information about the building, robot, user,
  destination, or environment.
- You cannot walk or move around, you are stationary.
- If someone wants a tour or navigation, tell them to connect to the BELT app.
- Earlier user and assistant messages are conversational context only. Do not
  treat an old action or navigation request as a new request.
- Do not output UCSC, output "U C Santa Cruz"
""".strip()


# ============================================================
# Client setup
# ============================================================

def create_llm_client() -> OpenAI:
    """
    Creates and returns a DeepSeek API client.

    Raises:
        RuntimeError: If DEEPSEEK_API_KEY is missing.
    """

    api_key = os.getenv("DEEPSEEK_API_KEY")

    if not api_key:
        raise RuntimeError(
            "Missing DEEPSEEK_API_KEY.\n"
            "Create a .env file containing:\n"
            "DEEPSEEK_API_KEY=your-api-key"
        )

    return OpenAI(
        api_key=api_key,
        base_url=DEEPSEEK_BASE_URL,
    )


# Create the client once when this file is imported.
LLM_CLIENT = create_llm_client()


# ============================================================
# History helpers
# ============================================================

def normalize_conversation(
    conversation: Optional[Sequence[Mapping[str, str]]],
) -> List[ConversationMessage]:
    """
    Returns the latest 10 user turns and their assistant responses.

    Conversation memory is supplied by the robot's main loop so internal
    detector and composer prompts never get mistaken for user history.
    """

    if conversation is None:
        return []

    if isinstance(conversation, (str, bytes)):
        raise TypeError("conversation must be a sequence of message objects")

    cleaned: List[ConversationMessage] = []
    for index, message in enumerate(conversation):
        if not isinstance(message, Mapping):
            raise TypeError(
                f"conversation item {index} must be a message object"
            )

        role = message.get("role")
        content = message.get("content")
        if role not in {"user", "assistant"}:
            raise ValueError(
                f"conversation item {index} has invalid role {role!r}"
            )
        if not isinstance(content, str):
            raise TypeError(
                f"conversation item {index} content must be a string"
            )

        content = content.strip()
        if content:
            cleaned.append({
                "role": role,
                "content": content,
            })

    user_indexes = [
        index
        for index, message in enumerate(cleaned)
        if message["role"] == "user"
    ]
    if len(user_indexes) > MAX_CONVERSATION_USER_INPUTS:
        cleaned = cleaned[user_indexes[-MAX_CONVERSATION_USER_INPUTS]:]

    return cleaned


def remember_conversation_turn(
    conversation: List[ConversationMessage],
    user_input: str,
    assistant_response: str,
) -> None:
    """Store a completed user/assistant turn and retain the latest 10."""
    user_input = user_input.strip()
    assistant_response = assistant_response.strip()

    if user_input:
        conversation.append({
            "role": "user",
            "content": user_input,
        })
    if assistant_response:
        conversation.append({
            "role": "assistant",
            "content": assistant_response,
        })

    conversation[:] = normalize_conversation(conversation)


def print_llm_history(
    conversation: Sequence[Mapping[str, str]],
) -> None:
    """
    Prints remembered user and assistant messages in a readable format.
    """

    recent_messages = normalize_conversation(conversation)
    if not recent_messages:
        print("No conversation messages are currently stored.")
        return

    print("\nRecent conversation:")

    for message in recent_messages:
        role = message["role"].capitalize()
        print(f"{role}: {message['content']}")

    print()


# ============================================================
# Main API function
# ============================================================

def call_llm(
    input_text: str,
    conversation: Optional[Sequence[Mapping[str, str]]] = None,
    debug: bool = False,
) -> Optional[str]:
    """
    Sends instructions or user text to the DeepSeek model.

    The function includes:
    - BELT's system prompt
    - The latest 10 user turns and BELT speech responses from ``conversation``
    - The current input

    If successful, it returns the LLM's text response.
    If the request fails, it prints an error and returns None.
    """

    input_text = input_text.strip()

    if not input_text:
        print("BELT API: Input text cannot be empty.")
        return None

    current_user_message = {
        "role": "user",
        "content": input_text,
    }

    recent_messages = normalize_conversation(conversation)
    messages = [
        {
            "role": "system",
            "content": BELT_SYSTEM_PROMPT,
        },
        *recent_messages,
        current_user_message,
    ]

    try:
        response = LLM_CLIENT.chat.completions.create(
            model=MODEL_NAME,
            messages=messages,
            stream=False,
        )

        choice = response.choices[0]
        output_text = choice.message.content

        if debug:
            print(f"Raw LLM response: {output_text!r}")

        if output_text is None:
            print("BELT API: The model returned an empty response.")
            return None

        output_text = output_text.strip()
        return output_text

    except AuthenticationError:
        print(
            "BELT API: DeepSeek rejected the API key. "
            "Check DEEPSEEK_API_KEY in your .env file."
        )

    except RateLimitError:
        print(
            "BELT API: Too many requests were sent. "
            "Please try again shortly."
        )

    except APIConnectionError:
        print(
            "BELT API: Could not connect to DeepSeek. "
            "Check your internet connection."
        )

    except APIStatusError as error:
        if error.status_code == 402:
            print(
                "BELT API: The DeepSeek account does not have "
                "enough available balance."
            )

        elif error.status_code in {500, 502, 503, 504}:
            print(
                "BELT API: DeepSeek's server is currently "
                "having problems."
            )

        else:
            print(
                f"BELT API: DeepSeek returned HTTP "
                f"{error.status_code}: {error}"
            )

    except Exception as error:
        print(f"BELT API: Unexpected error: {error}")

    return None


# ============================================================
# Terminal testing
# ============================================================

def main() -> None:
    print("BELT v3 LLM API loaded.")
    print("Commands: /quit, /clear, /history\n")
    conversation: List[ConversationMessage] = []

    while True:
        text_input = input("You: ").strip()

        if text_input == "/quit":
            print("Closing BELT v3.")
            break

        if text_input == "/clear":
            conversation.clear()
            print("BELT: Conversation history cleared.\n")
            continue

        if text_input == "/history":
            print_llm_history(conversation)
            continue

        response = call_llm(text_input, conversation=conversation)

        if response is not None:
            print(f"BELT: {response}\n")
            remember_conversation_turn(
                conversation,
                text_input,
                response,
            )


if __name__ == "__main__":
    main()
