'''
This was generated by ChatGPT, I lwk don't know how it works
The main function here is call_llm, where you input a text and it calls llm with the text
Also there's a system_prompt you can edit here
'''



from __future__ import annotations

import os
from collections import deque
from typing import Deque, Dict, List, Optional

from dotenv import load_dotenv
from openai import (
    APIConnectionError,
    APIStatusError,
    AuthenticationError,
    OpenAI,
    RateLimitError,
)


# ============================================================
# Configuration
# ============================================================

load_dotenv()

DEEPSEEK_BASE_URL = "https://api.deepseek.com"
MODEL_NAME = "deepseek-v4-flash"

# Stores the latest 10 individual user/assistant messages.
# The system prompt is stored separately and is not included
# in this limit.
MESSAGE_HISTORY: Deque[Dict[str, str]] = deque(maxlen=10)


BELT_SYSTEM_PROMPT = """
You are BELT, a UCSC campus receptionist robot.

Your job is to communicate with visitors in a friendly, helpful,
and concise way.

Personality:
- Friendly
- Curious
- Helpful
- Slightly witty
- Patient with beginners

Rules:
- Keep responses short unless the user asks for more detail.
- Do not claim that you can see something unless computer vision
  information was explicitly provided.
- Do not claim that you moved or navigated somewhere unless the
  corresponding robot module confirmed that it happened.
- If you are uncertain, clearly say that you are not sure.
- Never invent information about the building, robot, user,
  destination, or environment.
- You cannot walk or move around, you are stationary.
- If someone wants a tour or navigation, tell them to connect to the BELT app.
""".strip()


# ============================================================
# Client setup
# ============================================================

def create_llm_client() -> OpenAI:
    """
    Creates and returns a DeepSeek API client.

    Raises:
        RuntimeError: If DEEPSEEK_API_KEY is missing.
    """

    api_key = os.getenv("DEEPSEEK_API_KEY")

    if not api_key:
        raise RuntimeError(
            "Missing DEEPSEEK_API_KEY.\n"
            "Create a .env file containing:\n"
            "DEEPSEEK_API_KEY=your-api-key"
        )

    return OpenAI(
        api_key=api_key,
        base_url=DEEPSEEK_BASE_URL,
    )


# Create the client once when this file is imported.
LLM_CLIENT = create_llm_client()


# ============================================================
# History helpers
# ============================================================

def get_llm_history() -> List[Dict[str, str]]:
    """
    Returns a copy of the current conversation history.
    """

    return list(MESSAGE_HISTORY)


def clear_llm_history() -> None:
    """
    Clears all remembered user and assistant messages.
    """

    MESSAGE_HISTORY.clear()


def print_llm_history() -> None:
    """
    Prints the current history in a readable format.
    """

    if not MESSAGE_HISTORY:
        print("No messages are currently stored.")
        return

    print("\nCurrent LLM history:")

    for message in MESSAGE_HISTORY:
        role = message["role"].capitalize()
        content = message["content"]

        print(f"{role}: {content}")

    print()


# ============================================================
# Main API function
# ============================================================

def call_llm(input_text: str) -> Optional[str]:
    """
    Sends instructions or user text to the DeepSeek model.

    The function includes:
    - BELT's system prompt
    - The latest 10 user/assistant messages
    - The current input

    If successful, it returns the LLM's text response.
    If the request fails, it prints an error and returns None.
    """

    input_text = input_text.strip()

    if not input_text:
        print("BELT API: Input text cannot be empty.")
        return None

    current_user_message = {
        "role": "user",
        "content": input_text,
    }

    messages = [
        {
            "role": "system",
            "content": BELT_SYSTEM_PROMPT,
        },
        *list(MESSAGE_HISTORY),
        current_user_message,
    ]

    try:
        response = LLM_CLIENT.chat.completions.create(
            model=MODEL_NAME,
            messages=messages,
            stream=False,
        )

        output_text = response.choices[0].message.content

        if output_text is None:
            print("BELT API: The model returned an empty response.")
            return None

        output_text = output_text.strip()

        # Only save messages after a successful API call.
        MESSAGE_HISTORY.append(current_user_message)

        MESSAGE_HISTORY.append({
            "role": "assistant",
            "content": output_text,
        })

        return output_text

    except AuthenticationError:
        print(
            "BELT API: DeepSeek rejected the API key. "
            "Check DEEPSEEK_API_KEY in your .env file."
        )

    except RateLimitError:
        print(
            "BELT API: Too many requests were sent. "
            "Please try again shortly."
        )

    except APIConnectionError:
        print(
            "BELT API: Could not connect to DeepSeek. "
            "Check your internet connection."
        )

    except APIStatusError as error:
        if error.status_code == 402:
            print(
                "BELT API: The DeepSeek account does not have "
                "enough available balance."
            )

        elif error.status_code in {500, 502, 503, 504}:
            print(
                "BELT API: DeepSeek's server is currently "
                "having problems."
            )

        else:
            print(
                f"BELT API: DeepSeek returned HTTP "
                f"{error.status_code}: {error}"
            )

    except Exception as error:
        print(f"BELT API: Unexpected error: {error}")

    return None


# ============================================================
# Terminal testing
# ============================================================

def main() -> None:
    print("BELT v3 LLM API loaded.")
    print("Commands: /quit, /clear, /history\n")

    while True:
        text_input = input("You: ").strip()

        if text_input == "/quit":
            print("Closing BELT v3.")
            break

        if text_input == "/clear":
            clear_llm_history()
            print("BELT: Conversation history cleared.\n")
            continue

        if text_input == "/history":
            print_llm_history()
            continue

        response = call_llm(text_input)

        if response is not None:
            print(f"BELT: {response}\n")


if __name__ == "__main__":
    main()